"""
pitcher_model.paths
===================
Canonical locations for data, models, and generated output.

Every path is resolved from the repository root — derived from this file's
own location — rather than from the current working directory. That means a
script behaves identically whether it's invoked as

    python run.py predict strikeouts
    python -m pitcher_model.predict.strikeouts
    cd /somewhere/else && python /path/to/repo/run.py predict strikeouts

The previous layout used bare Path("data") in every script, which silently
resolved against the caller's cwd and only worked when run from the repo root.

None of these directories are in version control (see .gitignore); they are
created on demand and regenerated by the pipeline.
"""

from pathlib import Path

# pitcher_model/paths.py -> pitcher_model/ -> repository root
ROOT = Path(__file__).resolve().parent.parent

DATA_DIR = ROOT / "data"
MODEL_DIR = ROOT / "models"
OUTPUT_DIR = ROOT / "output"

# Alias: a few modules refer to the model directory in the plural.
MODELS_DIR = MODEL_DIR


def ensure_dirs(*dirs):
    """Create the given directories if absent; default to all three."""
    for d in (dirs or (DATA_DIR, MODEL_DIR, OUTPUT_DIR)):
        Path(d).mkdir(parents=True, exist_ok=True)


__all__ = ["ROOT", "DATA_DIR", "MODEL_DIR", "MODELS_DIR", "OUTPUT_DIR", "ensure_dirs"]
